data_config: 'mode_1'
model: 'CMamba_v1'

name: 'CMamba'
max_epochs: 500
use_volume: False
additional_features: ['Score']

hyperparams:
    optimizer: 'adam'
    lr: 0.01
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.0005