data_config: 'mode_1'
model: 'iTransformer_v'

name: 'itransformer'
max_epochs: 300
use_volume: True
additional_features: ['Score']

hyperparams:
    optimizer: 'adam'
    lr: 0.002
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.00001